[DEFAULT]
log_dir = /var/log/heat
use_stderr = False

[keystone_authtoken]
auth_url = http://127.0.0.1:5000

[database]
connection = mysql://heat:heat@localhost/heat

[paste_deploy]
api_paste_config = /etc/heat/api-paste.ini
